# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-11-10 18:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_m2', models.IntegerField()),
                ('thana', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('pressure', models.CharField(max_length=16)),
                ('dma_id', models.CharField(max_length=20)),
                ('package', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('area_sqkm', models.FloatField()),
                ('deviation', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
