# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-11-10 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0002_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='area_m2',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='area_sqkm',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='deviation',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='location',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='name',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='package',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='project',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='status',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='zone',
        ),
    ]
